import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getDatabase, ref, push, onValue } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';

const firebaseConfig={apiKey:'AIzaSyChmbRsz03i6RUdTep5kSxfwBmBXkgmcuk',authDomain:'my-chay.firebaseapp.com',databaseURL:'https://my-chay-default-rtdb.asia-southeast1.firebasedatabase.app',projectId:'my-chay',storageBucket:'my-chay.firebasestorage.app',messagingSenderId:'39896419588',appId:'1:39896419588:web:af181789ef1164bae35451',measurementId:'G-YXJD0SK4Y1'};
const app=initializeApp(firebaseConfig),db=getDatabase(app),auth=getAuth(app);
const recipe=(location.pathname.split('/').pop()||'recipe').replace(/\.html$/,'');
const style=document.createElement('style');style.textContent=`#qnaTab{position:fixed;right:0;top:42%;z-index:1001;background:#3182ce;color:#fff;border:0;border-radius:12px 0 0 12px;padding:14px 9px;writing-mode:vertical-rl;font-weight:bold;box-shadow:0 2px 8px #0003;cursor:pointer}#qnaPanel{position:fixed;right:-380px;top:0;width:min(380px,92vw);height:100dvh;background:#fff;z-index:1002;box-shadow:-5px 0 18px #0003;transition:right .25s;display:flex;flex-direction:column;font-family:inherit;color:#2d3748}#qnaPanel.open{right:0}.qnaHead{padding:16px;background:#3182ce;color:#fff;display:flex;justify-content:space-between;align-items:center}.qnaHead button{border:0;background:transparent;color:#fff;font-size:24px}.qnaList{flex:1;overflow:auto;padding:14px}.qnaItem{padding:12px 0;border-bottom:1px solid #e2e8f0}.qnaItem b{display:block;word-break:break-word}.qnaItem small{color:#718096}.qnaForm{padding:12px;border-top:1px solid #e2e8f0}.qnaForm input,.qnaForm textarea{width:100%;box-sizing:border-box;padding:9px;margin-bottom:7px;border:1px solid #cbd5e0;border-radius:7px;font:inherit}.qnaForm textarea{height:75px;resize:none}.qnaForm button{width:100%;padding:10px;border:0;border-radius:7px;background:#3182ce;color:#fff;font-weight:bold}.qnaMsg{padding:12px;color:#718096;font-size:13px}@media(max-width:600px){#qnaPanel{width:88vw}}`;document.head.appendChild(style);
const tab=document.createElement('button');tab.id='qnaTab';tab.textContent='💬 Q&A';document.body.appendChild(tab);
const panel=document.createElement('aside');panel.id='qnaPanel';panel.innerHTML=`<div class="qnaHead"><strong>💬 이 레시피 Q&A</strong><button id="qnaClose">×</button></div><div class="qnaList" id="qnaList"><div class="qnaMsg">불러오는 중...</div></div><form class="qnaForm" id="qnaForm"><input id="qnaName" maxlength="30" placeholder="이름 (선택)"><textarea id="qnaText" maxlength="500" required placeholder="요리하면서 궁금한 점을 입력하세요"></textarea><button>질문 등록</button></form>`;document.body.appendChild(panel);
const list=document.getElementById('qnaList');function open(){panel.classList.add('open');}function close(){panel.classList.remove('open');}tab.onclick=open;document.getElementById('qnaClose').onclick=close;
function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML;}
function render(data){list.innerHTML='';const rows=Object.values(data||{}).sort((a,b)=>(a.time||0)-(b.time||0));if(!rows.length){list.innerHTML='<div class="qnaMsg">아직 질문이 없습니다.</div>';return;}rows.forEach(x=>{const e=document.createElement('div');e.className='qnaItem';e.innerHTML=`<b>❓ ${esc(x.text||'')}</b><small>${esc(x.name||'익명')} · ${new Date(x.time||Date.now()).toLocaleString('ko-KR')}</small>`;list.appendChild(e);});}
async function start(){try{await signInAnonymously(auth);onValue(ref(db,`qna/${recipe}`),s=>render(s.val()),()=>{list.innerHTML='<div class="qnaMsg">Q&A를 불러오지 못했습니다.</div>';});}catch(e){console.error(e);list.innerHTML='<div class="qnaMsg">Firebase 인증이 필요합니다.</div>';}}
document.getElementById('qnaForm').onsubmit=async e=>{e.preventDefault();const text=document.getElementById('qnaText').value.trim();const name=document.getElementById('qnaName').value.trim()||'익명';if(!text)return;try{await push(ref(db,`qna/${recipe}`),{text,name,time:Date.now()});document.getElementById('qnaText').value='';}catch(err){alert('질문 등록에 실패했습니다. Firebase 보안 규칙을 확인해주세요.');}};
let sx=0;document.addEventListener('touchstart',e=>sx=e.changedTouches[0].screenX,{passive:true});document.addEventListener('touchend',e=>{const x=e.changedTouches[0].screenX;if(sx>innerWidth-70&&x-sx<-70)open();else if(x-sx>70&&panel.classList.contains('open'))close();},{passive:true});start();